### ISSUE TITLE
JsonSerializationException with status=grace

### ISSUE THREAD

**Issue by cuu508** [taylus/HealthTray#1]
Hello, 

kudos on this project! I discovered it just today, and gave it a test right away. I hit an issue the moment when one of the checks was transitioning from "up" to "grace" (orange) state:

![image](https://user-images.githubusercontent.com/661859/46605724-33d90080-cb03-11e8-8b70-873b5c06aa26.png)

**Comment by taylus** [comment]
It's the man himself!

Thank you for taking a look and reporting this issue, I will look into it.

**Comment by taylus** [comment]
Hey @cuu508, do you happen to know if the API used to return "late" when this happens, but now returns "grace" instead? I think this happened sometime in the last ~year and is what caused this to occur. I made a quick fix to treat both of those statuses the same. 

Thank you!

**Comment by cuu508** [comment]
Cool, will give this a test!

Yep, a change on the server side broke it. API responses used to return just two status values: `up` or `down`. This June I had added the third `grace` value: https://github.com/healthchecks/healthchecks/commit/5cf6f1b51e14e2348b0ff4346422d7cbaf835a31
